name: Package Application with Pyinstaller

on:
  workflow_dispatch: {}
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: '.'
    - uses: actions/upload-artifact@v2
      with:
        name: db-starter.exe
        path: dist/windows
